# docker/grafana/datasources/prometheus.yml
# Prometheus Data Source for Grafana

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
