# configs/services.example.yml
# Общая конфигурация для всех сервисов NovaSec

# Настройки NATS
nats:
  urls:
    - "nats://localhost:4222"
  cluster_id: "novasec"
  client_id: "novasec-service"
  credentials: ""  # Путь к файлу учетных данных NATS
  jwt: ""          # JWT токен для аутентификации
  nkey: ""         # NKey для аутентификации
  timeout: "30s"

# Настройки ClickHouse
clickhouse:
  hosts:
    - "localhost"
  database: "novasec"
  username: "default"
  password: ""
  port: 9000
  secure: false
  compress: true
  max_open: 100
  max_idle: 10
  timeout: "30s"

# Настройки PostgreSQL
postgresql:
  host: "localhost"
  port: 5432
  database: "novasec"
  username: "novasec"
  password: "novasec"
  ssl_mode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"

# Настройки Redis
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  timeout: "5s"

# Настройки SMTP для email уведомлений
smtp:
  host: "localhost"
  port: 587
  username: "noreply@novasec.local"
  password: ""
  from: "noreply@novasec.local"
  to: "admin@novasec.local"
  subject_prefix: "[NovaSec]"
  tls_enabled: true
  tls_insecure: false

# Настройки Telegram для уведомлений
telegram:
  enabled: false
  bot_token: ""
  chat_id: ""
  parse_mode: "HTML"
  disable_web_page_preview: true
  disable_notification: false

# Настройки Webhook для уведомлений
webhook:
  enabled: false
  url: ""
  method: "POST"
  timeout: "30s"
  headers:
    Content-Type: "application/json"
    User-Agent: "NovaSec/1.0"
  retry_count: 3
  retry_delay: "5s"

# Настройки правил подавления по умолчанию
suppression:
  default_suppress_window: "15m"
  max_suppress_window: "24h"
  cleanup_interval: "1h"
  max_suppressions_per_rule: 1000

# Настройки корреляции
correlation:
  max_window_size: "1h"
  min_window_size: "1s"
  max_events_per_window: 100000
  cleanup_interval: "5m"
  max_rules: 1000
  rule_reload_interval: "30s"

# Настройки алертов
alerts:
  max_alerts_per_rule: 10000
  alert_cleanup_interval: "1h"
  alert_retention_days: 90
  dedup_enabled: true
  dedup_window: "5m"
  max_dedup_keys: 10000

# Настройки событий
events:
  max_events_per_batch: 1000
  batch_timeout: "5s"
  event_retention_days: 180
  compression_enabled: true
  max_event_size: "1MB"

# Настройки логирования
logging:
  level: "info"
  format: "json"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Настройки TLS
tls:
  enabled: false
  ca_file: "configs/tls/ca.crt"
  cert_file: "configs/tls/service.crt"
  key_file: "configs/tls/service.key"
  min_version: "1.2"
  client_auth: "require_and_verify"

# Настройки метрик
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: "30s"
  retention_days: 30

# Настройки мониторинга
monitoring:
  health_check_interval: "30s"
  health_check_timeout: "10s"
  max_health_check_failures: 3
  alert_on_health_failure: true

# Настройки безопасности
security:
  max_login_attempts: 5
  lockout_duration: "15m"
  session_timeout: "8h"
  password_min_length: 12
  require_strong_passwords: true
  mfa_enabled: false

# Настройки производительности
performance:
  max_goroutines: 1000
  max_memory_usage: "1GB"
  gc_percent: 100
  max_cpu_usage: 80
